# works for ubuntu vm


AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  SSHLocation:
      Description: The IP address range that can be used to SSH to the EC2 instances
      Type: String
      MinLength: 9
      MaxLength: 18
      Default: 0.0.0.0/0
      AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
      ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.


Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.medium
      ImageId: ami-00874d747dde814fa
      KeyName: keypairname
      SecurityGroupIds:
        - !Ref MySecurityGroup
      SubnetId: subnet-xxxxxxx
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          echo "Copying install_prefect_ec2_Agent_bash.sh to the EC2 instance..."
          echo "Running install_prefect_ec2_Agent_bash.sh on the EC2 instance..."
          sh docker_install_run_bash.sh



  MySecurityGroup:
      Type: "AWS::EC2::SecurityGroup"
      Properties:
        GroupDescription: Allow HTTP and SSH traffic
        GroupName: ec2_prefect_sg
        VpcId: vpc-xxxxxxx
        SecurityGroupIngress:
          - IpProtocol: tcp
            FromPort: 22
            ToPort: 22
            CidrIp: !Ref 'SSHLocation'
          - IpProtocol: tcp
            FromPort: 80
            ToPort: 80
            CidrIp: 0.0.0.0/0
          - IpProtocol: tcp
            FromPort: 443
            ToPort: 443
            CidrIp: 0.0.0.0/0
